locastic_sylius_translations_admin_index:
    path: /
    methods: [ GET, POST ]
    controller: Locastic\SyliusTranslationPlugin\Controller\Admin\IndexTranslationAction

locastic_sylius_translation_admin_ajax_update:
    path: /ajax/update
    methods: [ POST ]
    controller: Locastic\SymfonyTranslationBundle\Controller\SaveTranslationsAction
