locastic_sylius_translations_admin_paths:
    prefix: /translations
    resource: 'routes/translations.yaml'

locastic_sylius_translations_admin_clear_cache:
    path: /clear-cache
    methods: [ GET ]
    controller: locastic_sylius_translation.controller.clear_cache_action
