locastic_sylius_translations_admin_paths:
    prefix: /translations
    resource: 'routes/translations.yaml'

locastic_sylius_translations_admin_clear_cache:
    path: /clear-cache
    methods: [ GET ]
    controller: Locastic\SyliusTranslationPlugin\Controller\Admin\ClearCacheAction
